version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "https://smile-api.mbn.dev"
        NEXT_PUBLIC_LOGO_URL: "https://img.logoipsum.com/244.svg"
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_LOGO_URL=${NEXT_PUBLIC_LOGO_URL}
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - PORT=3334
    ports:
      - 3334:3334
    # env_file:
    #   - ./apps/api/.env
